language: objective-c
osx_image: xcode12.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=Erik.xcworkspace
    - IOS_FRAMEWORK_SCHEME="Erik"
    - MACOS_FRAMEWORK_SCHEME="ErikOSX"
    - IOS_SDK=iphonesimulator14.2
    - MACOS_SDK=macosx11.0
  matrix:
    - DESTINATION="OS=14.2,name=iPhone 8" SCHEME="$IOS_FRAMEWORK_SCHEME" SDK="$IOS_SDK"
    - DESTINATION="arch=x86_64" SCHEME="$MACOS_FRAMEWORK_SCHEME" SDK="$MACOS_SDK"
before_install:
  - gem install xcpretty --no-document --quiet
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage build --no-skip-current
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
